Tjarbo/issue 102 webauthn
tjarbo/discord-moodle-bot pull request #104
Opened 2021-04-18 10:32 UTC by tjarbo

Moin,
as discussed this PR is a draft before the original PR. Please make sure the you are fine with the current implementation, before I will write unit tests. To get started, you can copy your existing .env or create a new from template (see wiki). You only have to add `RP_ORIGIN=http://localhost:4040` and adjust the port. The value must be the url where the the frontend is reachable.

2021-04-19 16:20 UTC, p-fruck approved these changes
Well done :+1:

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Dashboard.vue
> +          -->
```suggestion
```
Should this be removed to clean up code?

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Dashboard.vue
> +// import AdministratorList from '../components/administration/AdministratorList.vue';
```suggestion
```

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Dashboard.vue
> +    //    AdministratorList,
```suggestion
```

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Login.vue
> +      // Request assertion options from sever
```suggestion
      // Request assertion options from server
```

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Login.vue
> +                // Registration proccess timed out or cancled
```suggestion
                // Registration process timed out or cancelled
```

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Login.vue
> +            // Handle error during challange solving process
```suggestion
            // Handle error during challenge solving process
```

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Registration.vue
> +      subtitle="Registriere dich an, um fortzufahren!"
```suggestion
      subtitle="Registriere dich, um fortzufahren!"
```
:de: :P

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Registration.vue
> +            placeholder="Choose username"
```suggestion
            placeholder="Wähle Benutzername"
```

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Registration.vue
> +            placeholder="109156be-c4fb-41ea-b1b4-efe1671c5836"
Found a S3cr3t!!11 :P

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Registration.vue
> +      // Request attestation options from sever
```suggestion
      // Request attestation options from server
```

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Registration.vue
> +            // Handle error during challange solving process
```suggestion
            // Handle error during challenge solving process
```

2021-04-19 16:20 UTC, p-fruck commented on packages/frontend/src/views/Registration.vue
> +                // Registration proccess timed out or cancled
```suggestion
                // Registration process timed out or cancelled
```

2021-04-19 16:21 UTC, antonplagemann requested changes
Haben 30m reviewt... WIELANGE hast du dann zum programmieren gebraucht?? 😂 
Nice work 🏅

2021-04-19 16:21 UTC, antonplagemann commented on packages/backend/tests/auth.spec.ts
> +});
Newline!11!!

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Dashboard.vue
> +          -->
Wasn das?

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Dashboard.vue
> +// import AdministratorList from '../components/administration/AdministratorList.vue';
Wasn das?

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Dashboard.vue
> +    //    AdministratorList,
Wasn das?

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Login.vue
> +            placeholder="Your username"
```suggestion
            placeholder="Dein Benutzername"
```

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Login.vue
> -              >Brauchst du Hilfe?</a>
Help! I need Help! Lalalala...
#SinnloserComment

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Login.vue
> +            // Handle error during challange solving process
```suggestion
            // Handle error during challenge solving process
```

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Login.vue
> +                // Registration proccess timed out or cancled
```suggestion
                // Registration process timed out or cancelled
```

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Registration.vue
> +      subtitle="Registriere dich an, um fortzufahren!"
```suggestion
      subtitle="Registriere dich um fortzufahren!"
```

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Registration.vue
> +            placeholder="Choose username"
```suggestion
            placeholder="Wähle Deinen Benutzername"
```

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Registration.vue
> +            // Handle error during challange solving process
```suggestion
            // Handle error during challenge solving process
```

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Registration.vue
> +                // Registration proccess timed out or cancled
```suggestion
                // Registration process timed out or cancelled
```

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/src/views/Registration.vue
> +                notifyFailure('Authenticator wurde wahrscheinlich bereits von dir registriert!');
```suggestion
                notifyFailure('Authenticator wurde wahrscheinlich bereits von Dir registriert!');
```

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/tests/unit/views/login.view.spec.js
> +    expect(usernameInput.element.placeholder).to.be.equal('Your username');
```suggestion
    expect(usernameInput.element.placeholder).to.be.equal('Dein Benutzername');
```

2021-04-19 16:21 UTC, antonplagemann commented on packages/frontend/tests/unit/views/registration.view.spec.js
> +    expect(usernameInput.element.placeholder).to.be.equal('Choose username');
```suggestion
    expect(usernameInput.element.placeholder).to.be.equal('Wähle Deinen Benutzername');
```

2021-04-19 18:23 UTC, tjarbo commented
> Haben 30m reviewt... WIELANGE hast du dann zum programmieren gebraucht?? joy
> Nice work medal_sports

@antonplagemann @p-fruck vielen dank, dass ihr euch die Zeit genommen habt :raised_hands:  und so viele Kommentare hinterlassen habt. Wie lange ich gebraucht habe ? Locker drei bis 4 volle Tage dafür gebraucht :sweat_smile:

2021-04-19 20:12 UTC, tjarbo commented on packages/backend/src/controllers/authentication/registrationToken.schema.ts
> +    expires: '15m',
Done in bec854e

2021-04-20 08:38 UTC, tjarbo commented on packages/backend/src/routes/settings.routes.ts
> +// import { addAdministratorRequest, getAdministratorListRequest, deleteAdministratorRequest } from '../controllers/administrator';
This is okay, because these endpoints are just temporally disabled and will be reactivated in #103. To keep the consistency, I left the old code as comments

2021-04-20 09:13 UTC, tjarbo commented on packages/frontend/src/views/Registration.vue
> +      subtitle="Registriere dich an, um fortzufahren!"
#copypaste

2021-04-20 09:16 UTC, tjarbo commented on packages/frontend/src/views/Registration.vue
> +            placeholder="109156be-c4fb-41ea-b1b4-efe1671c5836"
AHHHHHHHH!!!!! oh wait, it's just a placeholder :laughing:

2021-04-20 09:32 UTC, tjarbo commented on packages/frontend/src/views/Registration.vue
> +                notifyFailure('Authenticator wurde wahrscheinlich bereits von dir registriert!');
Wie groß schreiben ?

2021-04-20 09:56 UTC, antonplagemann commented on packages/frontend/src/views/Registration.vue
> +                notifyFailure('Authenticator wurde wahrscheinlich bereits von dir registriert!');
Ne muss nicht, war mir dann doch unsicher :-)

2021-04-20 10:16 UTC, antonplagemann approved these changes

2021-04-20 14:04 UTC, merged