WIP: Reimplementing bots
tjarbo/discord-moodle-bot pull request #119
Opened 2021-05-09 20:26 UTC by tjarbo

This PR is related to #116! Before I will jump into writing tests and lose hours over hours I want to check that the current implementation is fine so far! So please do a *"prereview"* and try the following things:
* run it on our host machine and look if it creates a *DiscordBot* connector based on your env variables
* maybe you can find dead code, because some lines are now not used anymore
* maybe there are still missing newlines #philipp :grin: 
* it's great to see and test if there are enough comments. If you have some time available I would be happy if you would try to understand the code and what it does to let me know if there are any missing comments that can help to understand it better

Thank you :smile: and have a nice week!

2021-05-10 16:17 UTC, p-fruck commented on packages/backend/src/controllers/connectors/logger.ts
> +   * Print and stores a warning message
```suggestion
   * Prints and stores a warning message
```

2021-05-10 16:17 UTC, p-fruck commented on packages/backend/src/controllers/connectors/logger.ts
> +   * Print and stores a error message
```suggestion
   * Prints and stores a error message
```

2021-05-10 16:20 UTC, p-fruck commented on packages/backend/src/controllers/connectors/plugins/discordBot.class.ts
> +        connectorLogger.info('Successfully send message via Discord bot!', this.objectId);
```suggestion
        connectorLogger.info('Successfully sent message via Discord bot!', this.objectId);
```

2021-05-10 16:22 UTC, p-fruck commented on packages/backend/src/controllers/connectors/plugins/discordBot.class.ts
> +   * assigned courses.
```suggestion
   * Returns true, if the bot is a default handler for unassigned courses.
```

2021-05-10 16:23 UTC, p-fruck commented on packages/backend/src/controllers/connectors/service.ts
> +    // Get all connectors from Database
```suggestion
    // Get all connectors from database
```

2021-05-10 16:24 UTC, p-fruck commented on packages/backend/src/controllers/connectors/service.ts
> +        loggerFile.warn('Not connector found at database');
```suggestion
        loggerFile.warn('No connector found within database');
```

2021-05-10 16:27 UTC, p-fruck commented on packages/backend/src/controllers/connectors/service.ts
> +   * If the course is assigned to no course, it will send the message to all
```suggestion
   * If the course is not assigned to a connector, it will send the message to all
```

2021-05-10 16:28 UTC, p-fruck commented on packages/backend/src/controllers/connectors/service.ts
> +   * Throws ApiError
Isn't there some annotation like `@throws`?

2021-05-10 20:22 UTC, antonplagemann commented
Hi there :-)
Some questions that arose while testing:
- Web GUI is in german, but error notification 'user not found' or 'user not registered' is in english?
- What if I dont have a security key?
- Why is an unsuccessful registration attempt (aborted WebAuthn dialog) saved to the database?
![grafik](https://user-images.githubusercontent.com/54081139/117716308-b8b7b980-b1d9-11eb-9cbc-ece6bd69b1c3.png)
![grafik](https://user-images.githubusercontent.com/54081139/117717033-94a8a800-b1da-11eb-9e28-5e34b22f662f.png)
- Why is the statusboard currently empty?
Doing a code review later ;-)

2021-05-11 09:07 UTC, tjarbo commented
Thank you for your review!

@p-fruck 
I will put all requested changes into one commit if it's okay

@antonplagemann 
Yes, you are right. The problem with mixed languages are caused by our ongoing i18n. I will create missing user stories which address this problem, but they will be part of Version 3

What happen if a user has no security key ?  Hopefully this should not be a thing. Because many computers nowadays have a TPM that is used e.g. for Windows Hello and even all modern Smartphones can handle FIDO2. 
But of course there will be people, who have no access to FIDO. Than an investment into a security key is certainly well spent. 

The status board is currently empty because it can not handle the new response. But this in scope of the next user story (I should start to write them down instead of keeping them in mind :sweat_smile:)

2021-05-12 08:23 UTC, p-fruck requested changes

2021-05-12 08:23 UTC, p-fruck commented on packages/backend/src/controllers/connectors/logger.ts
> +   * Prints and stores a info message
```suggestion
   * Prints and stores an info message
```

2021-05-12 08:23 UTC, p-fruck commented on packages/backend/src/controllers/connectors/logger.ts
> +   * Prints and stores a error message
```suggestion
   * Prints and stores an error message
```

2021-05-13 16:37 UTC, antonplagemann requested changes
Looks fantastic 🔥 👍 😊

2021-05-13 16:37 UTC, antonplagemann commented on packages/backend/src/controllers/connectors/schemas/connectorLogItem.schema.ts
> +// TODO: Add expire date to envvar!
#ToDo :-)

2021-05-18 20:00 UTC, antonplagemann requested changes

2021-05-18 20:00 UTC, antonplagemann commented on packages/backend/src/controllers/connectors/plugins/connectorPlugin.class.ts
> +   * Returns the mongoDb objectId, this connector is build on.
```suggestion
   * Returns the mongoDB objectId, this connector is build on.
```

2021-05-18 20:00 UTC, antonplagemann commented on packages/backend/tests/connectors/logger.spec.ts
> +    spyLogger = jest.spyOn(loggerFile,'info');
```suggestion
    spyLogger = jest.spyOn(loggerFile, 'info');
```

2021-05-18 20:00 UTC, antonplagemann commented on packages/backend/tests/connectors/logger.spec.ts
> +  it('should save message to logs', () => {
```suggestion
  it('should save the message to logs', () => {
```

2021-05-18 20:00 UTC, antonplagemann commented on packages/backend/tests/connectors/logger.spec.ts
> +  it('should skip to save the message to logs', () => {
```suggestion
  it('should skip saving the message to logs', () => {
```

2021-05-18 20:00 UTC, antonplagemann commented on packages/backend/tests/connectors/logger.spec.ts
> +  it('should save message to logs', () => {
```suggestion
  it('should save the message to logs', () => {
```

2021-05-18 20:00 UTC, antonplagemann commented on packages/backend/tests/connectors/logger.spec.ts
> +  it('should skip to save the message to logs', () => {
```suggestion
  it('should skip saving the message to logs', () => {
```

2021-05-18 20:00 UTC, antonplagemann commented on packages/backend/tests/connectors/logger.spec.ts
> +  it('should save message to logs', () => {
```suggestion
  it('should save the message to logs', () => {
```

2021-05-18 20:00 UTC, antonplagemann commented on packages/backend/tests/connectors/logger.spec.ts
> +  it('should skip to save the message to logs', () => {
```suggestion
  it('should skip saving the message to logs', () => {
```

2021-05-19 19:37 UTC, antonplagemann approved these changes

2021-05-20 12:56 UTC, p-fruck approved these changes

2021-05-20 13:33 UTC, merged