🔖 Release 1.0.2
tjarbo/discord-moodle-bot pull request #154
Opened 2021-07-24 13:21 UTC by tjarbo

As Dependabot has submitted many dependency updates in the last time, we should release a new version to update the docker images.

## Changelog

* ⬆️ Bump docker/metadata-action from 3.4.0 to 3.4.1 (#153) @dependabot
* ⬆️ Bump docker/metadata-action from 3.3.0 to 3.4.0 (#150) @dependabot
* ⬆️ Bump actions/setup-node from 2.1.5 to 2.2.0 (#148) @dependabot
* ⬆️ Bump normalize-url from 4.5.0 to 4.5.1 in /packages/backend (#140) @dependabot
* ⬆️ Bump glob-parent from 5.1.1 to 5.1.2 in /packages/backend (#141) @dependabot
* ⬆️ Bump postcss from 7.0.35 to 7.0.36 in /packages/frontend (#142) @dependabot
* ⬆️ Bump ws from 6.2.1 to 6.2.2 in /packages/frontend (#139) @dependabot
* ⬆️ Bump ws from 7.3.1 to 7.4.6 in /packages/backend (#137) @dependabot
* ⬆️ Bump dns-packet from 1.3.1 to 1.3.4 in /packages/frontend (#136) @dependabot
* ⬆️ Bump browserslist from 4.12.0 to 4.16.6 in /packages/frontend (#135) @dependabot
* ⬆️ Bump docker/metadata-action from 3.2.0 to 3.3.0 (#138) @dependabot

2021-07-26 21:07 UTC, antonplagemann approved these changes
Checks and merge conflicts, everything else looks good 👍 💯

2021-07-29 21:27 UTC, piuswalter approved these changes

2021-07-29 21:34 UTC, piuswalter approved these changes

2021-07-29 21:34 UTC, piuswalter commented on .github/workflows/create-issue-branch.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```suggestion
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

2021-07-29 21:34 UTC, piuswalter commented on .github/workflows/release-drafter.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```suggestion
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

2021-07-29 21:36 UTC, p-fruck requested changes

2021-07-29 21:36 UTC, p-fruck commented on .github/workflows/create-issue-branch.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
newline!

2021-07-29 21:36 UTC, p-fruck commented on .github/workflows/release-drafter.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
newline!

2021-07-29 21:36 UTC, p-fruck commented on packages/backend/src/controllers/moodle/handle.ts
> +    return new Date(timestamp * 1000).toLocaleString('de-DE', dateOptions);
```suggestion
    return new Date(timestamp * 1000).toLocaleString(config.langFormat || unknown, dateOptions);
```
Not an actual suggestion, but at one point in time we should think about i18n support for our backend

2021-09-03 18:33 UTC, tjarbo commented on packages/backend/src/controllers/moodle/handle.ts
> +    return new Date(timestamp * 1000).toLocaleString('de-DE', dateOptions);
Sure, feel free to start #126 #127 :yum: But yeah, you are right.

2021-09-07 15:05 UTC, p-fruck approved these changes

2021-09-07 16:36 UTC, merged