✨ Add new connector
tjarbo/discord-moodle-bot pull request #164
Opened 2021-09-03 21:03 UTC by tjarbo

> **As a** User
> **I want** to add a new connector
> **so that** I can notify my friends on different platforms

## Description
With this PR it is possible to add further connectors! Unfortunately, right now only from type discord but hopefully more are coming soon. Please have look for typos, missing translations, etc but also for security relevant topics! Maybe you have even time to try out the web interface :innocent: 

Thank you! 

PS: Sorry for those many changes, the PR covers some bug fixed too - remaining from the last PRs :roll_eyes: 

### Screenshots
![grafik](https://user-images.githubusercontent.com/16938041/132064337-5e9b8865-c16c-484e-a2e6-3e13c83799cc.png)
![grafik](https://user-images.githubusercontent.com/16938041/132064370-7a0bf12d-9849-406d-be2f-aecbdfb9603d.png)

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

- [ ] ~Make sure you are requesting to main. Don't request to release branch!~
- [X] I have linked the related issue.
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2021-09-06 10:21 UTC, p-fruck requested changes
Nice work :+1: I'd like to suggest some changes, mostly consistency related and partly translational ;)

2021-09-06 10:21 UTC, p-fruck commented on packages/backend/src/controllers/connectors/handlers.ts
> + * @param next NextFunction
```suggestion
 * @param {Request} req Request
 * @param {Response} res Response
 * @param {NextFunction} next NextFunction
```

Just for consistency it would be nice to add the type definition (or remove it in all places, since it actually is not required when using typescript).

2021-09-06 10:21 UTC, p-fruck commented on packages/backend/tslint.json
>  }
newline :)

2021-09-06 10:21 UTC, p-fruck commented on packages/frontend/src/components/connectors/ConnectorCreate.vue
> +                        <span v-html="$t('components.connectorCreate.selectTypeBotsDiscordDescription', [ 'https://docs.tjarbo.me' ])" />
I would like to see this url in a separate config file, so in case of any change (or multiple occurence of the url in different parts of the code) it can be changed more easily

2021-09-06 10:21 UTC, p-fruck commented on packages/frontend/src/components/connectors/ConnectorCreate.vue
> +      }
```suggestion
    setResult(success) {
      this.loading.active = false;
      if (success) {
        this.loading.text = this.$t('components.connectorCreate.doneSuccessDescription');
        this.loading.icon = 'check-circle';
        this.loading.color = 'is-success';
      } else {
        this.loading.text = this.$t('components.connectorCreate.doneFailedDescription');
        this.loading.icon = 'times-circle';
        this.loading.color = 'is-danger';
      }
```
The duplicate declaration of `loading.active = false` can be circumvented

2021-09-06 10:21 UTC, p-fruck commented on packages/frontend/src/components/connectors/sockets/DiscordSocket.vue
> +    <p class="my-4" v-if="showDescription" v-html="$t('components.discordSocket.description', ['https://docs.tjarbo.me'])"></p>
Again, the hardcoded url is used.

2021-09-06 10:21 UTC, p-fruck commented on packages/frontend/src/locales/de.json
> +      "parametersConnectorName": "Connector Name:",
Organizational question: Should colons be handled by the translation or within the html template?

2021-09-06 10:21 UTC, p-fruck commented on packages/frontend/src/locales/de.json
> +      "selectTypeBotsDiscordDescription": "Für diesen Connetor musst du einen neuen Bot im Discord Developer Portal anlegen. Mehr dazu findest du <a href=\"{0}\">hier</a>",
```suggestion
      "selectTypeBotsDiscordDescription": "Für diesen Connector musst du einen neuen Bot im Discord Developer Portal anlegen. Mehr dazu findest du <a href=\"{0}\">hier</a>",
```

2021-09-06 10:21 UTC, p-fruck commented on packages/frontend/src/locales/en.json
> +      "selectTypeContent": "You want to create a new connector? Great! First, choose your wanted type from the list below:",
```suggestion
      "selectTypeContent": "You want to create a new connector? Great! First, choose your desired type from the list below:",
```
translation suggestion

2021-09-06 10:21 UTC, p-fruck commented on packages/frontend/src/locales/en.json
> +      "description": "Please enter the required values into the form. If problem occurs or you do not know what to do - You can find a manual <a href=\"{0}\">here</a>",
Sounds a bit strange. I would suggest either
```suggestion
      "description": "Please enter the required values into the form. If a problem occurs or you do not know what to do - You can find a manual <a href=\"{0}\">here</a>",
```

or

```suggestion
      "description": "Please enter the required values into the form. If problems occur or you do not know what to do - You can find a manual <a href=\"{0}\">here</a>",
```

2021-09-06 20:56 UTC, tjarbo commented on packages/frontend/src/locales/de.json
> +      "parametersConnectorName": "Connector Name:",
@p-fruck Hm, good point. There are pro and cons, but I would say, that they can be compared with punctuation marks like ! or ? which are already handled by the translation. So I would let them be handled by the translation.

Do you have an idea for an argument against?

2021-09-06 21:04 UTC, tjarbo commented on packages/frontend/src/components/connectors/ConnectorCreate.vue
> +                        <span v-html="$t('components.connectorCreate.selectTypeBotsDiscordDescription', [ 'https://docs.tjarbo.me' ])" />
@p-fruck That is a good point 👍! I will have to check, how this can be implemented as the links heavily depend on the url, version and the document name.

2021-09-06 21:12 UTC, tjarbo commented on packages/backend/src/controllers/connectors/handlers.ts
> + * @param next NextFunction
Hm, strange :thinking: I do not know, why there are missing as they are auto generated :sweat_smile: Well spotted!

2021-09-06 21:14 UTC, tjarbo commented on packages/frontend/src/components/connectors/sockets/DiscordSocket.vue
> +    <p class="my-4" v-if="showDescription" v-html="$t('components.discordSocket.description', ['https://docs.tjarbo.me'])"></p>
I will mark this conversation as resolved for a better overview. Continue on https://github.com/tjarbo/discord-moodle-bot/pull/164#discussion_r702782545

2021-09-06 21:51 UTC, p-fruck commented on packages/frontend/src/locales/de.json
> +      "parametersConnectorName": "Connector Name:",
Not really, except for inconsistency when one translation forgets to add the colon. On the other hand, it is pretty ugly to have the colon separated in the template. I guess leaving them in the translation is the better way to go in the long term...

2021-09-06 21:52 UTC, p-fruck approved these changes

2021-09-07 17:10 UTC, tjarbo commented on packages/backend/tslint.json
>  }
Added in b328cee

2021-09-07 17:28 UTC, tjarbo commented on packages/frontend/src/components/connectors/ConnectorCreate.vue
> +                        <span v-html="$t('components.connectorCreate.selectTypeBotsDiscordDescription', [ 'https://docs.tjarbo.me' ])" />
Fixed in 725c037

2021-09-07 17:33 UTC, tjarbo commented on packages/frontend/src/components/connectors/ConnectorCreate.vue
> +      }
Fixed, but moved the line below to the if statement as it triggers ui changes

2021-09-07 17:36 UTC, tjarbo commented
Thank you very much for your review @p-fruck!
 @antonplagemann or @piuswalter: Can any of you look over the code as well this week?

2021-09-13 14:03 UTC, piuswalter requested changes

2021-09-13 18:00 UTC, piuswalter approved these changes

2021-09-24 09:37 UTC, merged