🌐⚡️ Improved notification messages
tjarbo/discord-moodle-bot pull request #192
Opened 2022-01-12 17:15 UTC by tjarbo

> **As a** User
> **I want to** set the language of the notification messages
> **because** I cannot speak German

> **As a** Developer
> **I want to** use Handlebar.js for the message templates
> **because** it is minimal templating on steroids

## Description
This pull request was originally for #108. But because more and more users have forked the project to add an English translation, it was a minimal additional work to add i18n for the notification messages #127. Now, the user can decide whether to use the English or German notifications. But the new feature is a new `Message` class. It is extendable with new `getters` to provide different return types for different connectors (not only Markdown text).

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

- [ ] Make sure you are requesting to main. Don't request to release branch!
- [X] I have linked the related issue.
- [ ] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-01-12 20:55 UTC, antonplagemann requested changes
👏 ⭐

2022-01-12 20:55 UTC, antonplagemann commented on packages/backend/src/configuration/environment.ts
> +    .description('Defines the language the notification messages will be displayed.'),
```suggestion
    .description('Defines the language for all notification messages.'),
```

2022-01-12 20:55 UTC, antonplagemann commented on packages/backend/src/locales/de.json
> +}
```suggestion
}

```

2022-01-12 20:55 UTC, antonplagemann commented on packages/backend/src/locales/en.json
> +}
```suggestion
}

```

2022-01-13 06:38 UTC, piuswalter requested changes

2022-01-13 06:38 UTC, piuswalter commented on packages/backend/src/configuration/environment.ts
> +    .description('URL of your Moodle instance, eg. https://moodle.domain.me .'),
```suggestion
    .description('URL of your Moodle instance, eg. https://moodle.example.com .'),
```
Is this supposed to be advertising otherwise I would use the `example.com` domain.

2022-01-13 06:38 UTC, piuswalter commented on packages/backend/src/configuration/environment.ts
> +    .description('Interval to look for updates on moodle (in ms).'),
```suggestion
    .description('Interval to look for updates on Moodle (in ms).'),
```
Only for uniform wording.

2022-01-13 09:55 UTC, p-fruck requested changes

2022-01-13 09:55 UTC, p-fruck commented on packages/backend/src/controllers/messages/message.class.ts
> +  public get Markdown() : string {
```suggestion
  public get markdown() : string {
```

Wouldn't the naming convention suggest a getter to start with a lower-case letter?

2022-01-13 09:55 UTC, p-fruck commented on packages/backend/src/controllers/messages/templates/assignmentMessage.class.ts
> +  }
Is there a specific reason not to pass the context directly to the constructor of the super class?

2022-01-13 14:45 UTC, tjarbo commented on packages/backend/src/controllers/messages/message.class.ts
> +  public get Markdown() : string {
Hm, I do not know 🤔 The naming conventions do not really say something about this, AirBnB (style guide) instead recommend to avoid getter/setters (Ähm ... nope 😆). So I thought it would be a great idea to make a small visual separation from these computed getters compared with other basic properties. In future, there will be getters for:

| PascalCase            | camelCase             |
|-----------------------|-----------------------|
| `message.Embeds`      | `message.embeds`      |
| `message.AdaptiveKit` | `message.adaptiveKit` |
| `message.BlockKit`    | `message.blockKit`    |
| `message.HTML`        | `message.html`        |

What do you @p-fruck think is better? I am not really sure 😅

2022-01-13 14:56 UTC, tjarbo commented on packages/backend/src/controllers/messages/templates/assignmentMessage.class.ts
> +  }
@p-fruck 
I think there was one, but I am not 100% sure anymore. I will test the implementation and if it works, I will add the commit

2022-01-13 15:15 UTC, tjarbo commented on packages/backend/src/controllers/messages/templates/assignmentMessage.class.ts
> +  }
It works! Done with abbbfd6

2022-01-13 15:25 UTC, antonplagemann approved these changes

2022-01-13 15:29 UTC, p-fruck commented on packages/backend/src/controllers/messages/message.class.ts
> +  public get Markdown() : string {
@tjarbo In my opinion getters and setters should be represented as if they were regular attributes, regardless whether they require additional computation or not, which is why I would propose them to be written in camelCase. But this is just my personal opinion, I could be completely wrong about that :laughing:

2022-01-13 15:30 UTC, p-fruck approved these changes

2022-01-13 15:43 UTC, tjarbo commented on packages/backend/src/controllers/messages/message.class.ts
> +  public get Markdown() : string {
Okay, I agree with you. Renamed it in 7cf5ed5

2022-01-13 15:45 UTC, p-fruck approved these changes

2022-01-13 16:42 UTC, antonplagemann approved these changes

2022-01-13 17:15 UTC, piuswalter approved these changes

2022-01-13 17:19 UTC, merged

2022-01-13 17:20 UTC, tjarbo commented
Thank you 🎉! @piuswalter @p-fruck @antonplagemann