⚡️ Migrate from tslint to eslint
tjarbo/discord-moodle-bot pull request #193
Opened 2022-01-16 14:21 UTC by tjarbo

## Description
As described in #105, tslint is deprecated and is now replaced by eslint. I have followed [this guide](https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration) from Microsoft. Eslint is working, doing its job and improved the code 👍. As a side effect, it was required to migrate from the depreacted `@hapi/joi` to the new `joi` package which has a better TypeScript support. The project now follows the AirBnB style like the frontend. I have overwritten the rules of `@typescript-eslint/no-unsafe-member-access`, `@typescript-eslint/no-explicit-any` and `@typescript-eslint/no-unsafe-assignment` to not throw an error instead to print a warning based on a recommendation by @p-fruck.

Please review:
* Many things are just auto fixes, so ~60% of the review will be quick. The other 40% are new TypeScript code. **Please have a close look on these changes** and add a change request if you think there is a better naming,way of implementation etc. 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Checklist

- [X] Make sure you are requesting to main. Don't request to release branch!
- [X] I have linked the related issue.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-01-16 15:32 UTC, p-fruck requested changes
I mentioned the use of `eslint-disable` a couple of times, because imho this should be avoided as much as possible. You can disable and linescope certain rules, but I personally do not like to have eslint disabled for whole files.

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/configuration/logger.ts
> +    } },
```suggestion
      },
    },
    file: {
      type: 'file',
      filename: 'log/server.log',
      maxLogSize: 10485760,
      layout: {
        type: 'pattern',
        pattern: '[%d{ISO8601}] [%p] %m',
      },
    },
  },
```
Is this weird indentation intended? :smile:

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/controllers/connectors/logger.ts
> +   * Creates a new ConnectorLogItem and save it to the database.
```suggestion
   * Creates a new ConnectorLogItem and saves it to the database.
```

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/controllers/connectors/logger.ts
> +   * @return {Promise<void>} Return nothing
```suggestion
   * @param content
   * @return Return nothing
```
Jsdoc type annotations are not specified for the majority of the other functions because of typescript. We should handle this consistently

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/controllers/courseList/courseList.schema.ts
> +/* eslint-disable */
```suggestion
```
Do you really want to disable eslint for the whole file?

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/controllers/courseList/courseList.ts
> +/* eslint-disable */
```suggestion
```
Do you really want to disable eslint for the whole file?

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/controllers/moodle/fetch.ts
> +/* eslint-disable */
```suggestion
```
Do you really want to disable eslint for the whole file?

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/controllers/moodle/handle.ts
> +/* eslint-disable */
```suggestion
```
Do you really want to disable eslint for the whole file?

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/controllers/moodle/index.ts
> +/* eslint-disable */
```suggestion
```
Do you really want to disable eslint for the whole file?

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/controllers/moodle/refreshRate.ts
> +/* eslint-disable */
```suggestion
```
Do you really want to disable eslint for the whole file?

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/controllers/moodle/schemas/moodle.schema.ts
> +/* eslint-disable */
```suggestion
```
Do you really want to disable eslint for the whole file?

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/controllers/moodle/schemas/moodle.schema.ts
> +  if (!moodle || !moodle.refreshRate) {
```suggestion
  if (!moodle?.refreshRate) {
```
Why not simplify this condition?

2022-01-16 15:32 UTC, p-fruck commented on packages/backend/src/controllers/moodle/schemas/reminder.schema.ts
> +/* eslint-disable */
```suggestion
```
Do you really want to disable eslint for the whole file?

2022-01-16 16:23 UTC, tjarbo commented on packages/backend/src/controllers/moodle/schemas/moodle.schema.ts
> +  if (!moodle || !moodle.refreshRate) {
As I am not 100% sure that this covered by a uni test, I will reject this recommendation because it is not inscope of this pr. I will keep this in mind for the next implementation

2022-01-16 16:24 UTC, tjarbo commented
Please ignore global `eslint-disable` statements as these are only located in moodle related files which will be refactiored with further updates

2022-01-16 16:34 UTC, p-fruck approved these changes

2022-01-17 17:40 UTC, piuswalter requested changes

2022-01-17 17:40 UTC, piuswalter commented on packages/backend/.eslintrc.js
> +        "node": true
```suggestion
        "node": true,
```

2022-01-17 17:40 UTC, piuswalter commented on packages/backend/.eslintrc.js
> +        "airbnb-typescript/base"
```suggestion
        "airbnb-typescript/base",
```

2022-01-17 17:40 UTC, piuswalter commented on packages/backend/.eslintrc.js
> +        "@typescript-eslint"
```suggestion
        "@typescript-eslint",
```

2022-01-17 17:40 UTC, piuswalter commented on packages/backend/.eslintrc.js
> +    }
```suggestion
    },
```

2022-01-17 17:40 UTC, piuswalter commented on packages/backend/src/configuration/express.ts
> +  windowMs: 60 * 1000, // 1 minutes
```suggestion
  windowMs: 60 * 1000, // 1 minute
```

2022-01-17 17:40 UTC, piuswalter commented on packages/backend/src/configuration/logger.ts
>  };
```suggestion
  },
};
```

2022-01-18 08:08 UTC, piuswalter approved these changes

2022-01-18 08:41 UTC, merged