📝 Updated api documentation
tjarbo/discord-moodle-bot pull request #200
Opened 2022-02-05 19:35 UTC by tjarbo

## Description
As part of #130, many api endpoints were replaced by new ones. This updated includes the updated version of the api documentation available on `/api/docs`. I double checked it to ensure every endpoint is correctly displayed but maybe you have the time to check this again - it always easy to overlook something 😅 Thank you!

The documentation is buold with stoplight.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X] Documentation content changes
- [ ] Other (please describe):

## Checklist

- [X] Make sure you are requesting to main. Don't request to release branch!
- [ ] I have linked the related issue.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-02-05 20:28 UTC, tjarbo commented
@p-fruck you mentationed, that you know a package that uses jsdocs comments or something like that to generate an api docu from comments - which was it ?

2022-02-06 02:30 UTC, p-fruck commented
@tjarbo once upon a time I used to use `swagger-jsdoc` in combination with `swagger-express-ui`. StudyOffline is an example project using this setup. You can see the [swagger-ui](https://github.com/piuswalter/StudyOffline/blob/main/backend/src/routes/docs/docs.controller.ts) being served using express as well as our swagger documentation being [written inline](https://github.com/piuswalter/StudyOffline/blob/main/backend/src/routes/users/users.router.ts) as comments for the express router functions. Note that the swagger documentation is generated at runtime, not at compile time, in the example project.

2022-02-06 02:41 UTC, p-fruck requested changes

2022-02-06 02:41 UTC, p-fruck commented on packages/backend/src/docs/rest-api.json
> +          "description": "This endpoint allows to test if the peovided authentification token is valid or not",
```suggestion
          "description": "This endpoint allows to test if the provided authentication token is valid or not",
```

2022-02-06 02:41 UTC, p-fruck commented on packages/backend/src/docs/rest-api.json
> +          "description": "This endpoint allows to test if the peovided authentification token is valid or not",
```suggestion
          "description": "This endpoint allows to test if the provided authentification token is valid or not",
```
Not quite sure whether you want to keep the term `authentification`. Sounds weird to me, but since the tag is also called `Authentification`, at least it looks consistently weird :) We had this discussion before, hadn't we? :sweat_smile:

2022-02-06 02:41 UTC, p-fruck commented on packages/backend/src/docs/rest-api.json
> +          "description": "Removes the connector. Keep in mind, that if there is no connector configuered, the service will try to create new connectors based on the environment variables.",
```suggestion
          "description": "Removes the connector. Keep in mind, that if there is no connector configured, the service will try to create new connectors based on the environment variables.",
```

2022-02-06 02:41 UTC, p-fruck commented on packages/backend/src/docs/rest-api.json
> +        "description": "This is structure of the default response body. The code field is equal with the HTTP status code. The object field is either of type array or object, depending on the endpoin
```suggestion
        "description": "This is the structure of the default response body. The code field is equal with the HTTP status code. The object field is either of type array or object, depending on the endpoint.",
```

2022-02-06 02:41 UTC, p-fruck commented on packages/backend/src/docs/rest-api.json
> +        "description": "Invalid Request! Common reason is that the request body does not meet the expected struture. Make shure to check the api documentation. More information are available within t
```suggestion
        "description": "Invalid Request! Common reason is that the request body does not meet the expected structure. Make sure to check the api documentation. More information are available within the HTTP response ",
```

2022-02-06 02:41 UTC, p-fruck commented on packages/backend/src/docs/rest-api.json
> +        "description": "Oh no, an internal server error happend :/ Please check the server logs for further information!",
```suggestion
        "description": "Oh no, an internal server error occurred :/ Please check the server logs for further information!",
```

2022-02-06 02:41 UTC, p-fruck commented on packages/backend/src/docs/rest-api.json
> +  }
I like to complain about newline, but for some reasons vscode removes them automatically from json documents. Actually, the reason is quite valid, but nevertheless I'd like to request this newline.

2022-02-06 09:33 UTC, tjarbo commented on packages/backend/src/docs/rest-api.json
> +          "description": "This endpoint allows to test if the peovided authentification token is valid or not",
@p-fruck no, you are absolutly right! This is a good example why pr reviews are important. I will update everything

2022-02-06 09:46 UTC, tjarbo commented on packages/backend/src/docs/rest-api.json
> +  }
Added with [180b964](https://github.com/tjarbo/discord-moodle-bot/pull/200/commits/180b9649c582f5b7e3dfdc5f0e2e37be0f4a146f)

2022-02-06 12:48 UTC, p-fruck requested changes

2022-02-06 12:48 UTC, p-fruck commented on packages/backend/src/docs/rest-api.json
> +        "description": "Returns a list of all courses with the status whether the associated notifications are enabled or disabled.",
```suggestion
        "description": "Returns a list of all courses including a status indicating whether the associated notifications are enabled or disabled.",
```
Overlooked this last time :smile:

2022-02-06 12:48 UTC, p-fruck commented on packages/backend/src/docs/rest-api.json
> +        "description": "This endpoint returns a list of all configuered connectors.",
```suggestion
        "description": "This endpoint returns a list of all configured connectors.",
```

2022-02-06 12:48 UTC, p-fruck commented on packages/backend/src/docs/rest-api.json
> +            "description": "Connector created! Attribute \"data\" will contain the new connector object. ",
```suggestion
            "description": "Connector created! Attribute \"data\" will contain the new connector object.",
```

2022-02-06 12:48 UTC, p-fruck commented on packages/backend/src/docs/rest-api.json
> +      "description": "This is the structure of the default response body. The code field is equal with the HTTP status code. The object field is either of type array or object, depending on the endpo
```suggestion
      "description": "This is the structure of the default response body. The code field is equal to the HTTP status code. The object field is either of type array or object, depending on the endpoint.",
```

2022-02-06 13:46 UTC, p-fruck approved these changes

2022-02-06 13:47 UTC, merged