Feature/issue 41
tjarbo/discord-moodle-bot pull request #48
Opened 2020-08-20 17:52 UTC by tjarbo

> **Als ein** Entwickler
> **will ich** einheitliche Response-Objekte haben und VUEX im Frontend verwenden
> **sodass** die Dokumentation kleiner wird und Daten über Komponenten hinweg geteilt werden

## Beschreibung

Diese PR bringt finale Änderungen in Sachen REST-API. Ich habe eine ApiResponse-Klasse hinzugefügt, damit alle Antworten vom Server einheitlich verlaufen und leichter verarbeiten werden können. Alle Anfragen vom Client aus laufen nun über den VUEX Store. Das vereinfacht die Verwendung von `<b-loading>`, einer Ladeanzeige mit der ein entsprechendes Panel blockiert wird, wenn eine Anfrage gerade durchgeführt wird. Anschließend erfolgt nun an jede Anfrage eine Benachrichtigung, um die Erfolgreich war oder mit einem Fehler endete.

Closes #41 

Momentan ist die Dokumentation noch defekt. Diese wird aber in einem separatem Isssue behandelt werden. 

### Art der Änderungen:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [X] Documentation content changes
- [ ] Other (please describe):

## Checkliste

- [X] Make sure you are requesting to development. Don't request to master branch!
- [X] I have linked the related issue.
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2020-08-20 18:08 UTC, antonplagemann commented
> Diese PR bringt finale Änderungen in Sachen REST-API. Ich habe eine ApiResponse-Klasse hinzugefügt, damit alle Antworten vom Server einheitlich verlaufen und leichter verarbeiten werden können. Alle Anfragen vom Client aus laufen nun über den VUEX Store. Das vereinfacht die Verwendung von `<b-loading>`, einer Ladeanzeige mit der ein entsprechendes Panel blockiert wird, wenn eine Anfrage gerade durchgeführt wird. Anschließend erfolgt nun an jede Anfrage eine Benachrichtigung, um die Erfolgreich war oder mit einem Fehler endete.

Den letzten Satz evtl. noch mal anpassen ;-)

2020-08-20 18:10 UTC, antonplagemann requested changes
Merge conflict :-)

2020-08-20 18:58 UTC, tjarbo commented
@antonplagemann done :white_check_mark:

2020-08-20 19:41 UTC, antonplagemann requested changes
Sieht echt top aus 😎 
Gibt nur wenige Sachen die du noch mal _überpüfen_ kannst ;-)

2020-08-20 19:41 UTC, antonplagemann commented on packages/backend/src/docs/rest-api.yml
> -- "https"
Könnte mir dann vorstellen das man die Doku dann nicht mehr aktiv benutzen kann wie in unserer Livedemo wenn du HTTPS rauswirfst...

2020-08-20 19:41 UTC, antonplagemann commented on packages/frontend/src/components/administration/AddAdministrator.vue
> +              'Anfrage fehlgeschlagen! Bitte überpüfe deine Internetverbindung.',
```suggestion
              'Anfrage fehlgeschlagen! Bitte überprüfe deine Internetverbindung.',
```

2020-08-20 19:41 UTC, antonplagemann commented on packages/frontend/src/App.vue
> +        notifyFailure('Zugang leider abgelaufen. Bitte erneut anmelden');
```suggestion
        notifyFailure('Zugang leider abgelaufen. Bitte erneut anmelden!');
```

2020-08-20 19:41 UTC, antonplagemann commented on packages/frontend/src/components/discord/DiscordPanel.vue
> +              'Anfrage fehlgeschlagen! Bitte überpüfe deine Internetverbindung.',
```suggestion
              'Anfrage fehlgeschlagen! Bitte überprüfe deine Internetverbindung.',
```

2020-08-20 19:41 UTC, antonplagemann commented on packages/frontend/src/components/moodle/SetCourseNotifications.vue
> +            'Anfrage fehlgeschlagen! Bitte überpüfe deine Internetverbindung.',
```suggestion
            'Anfrage fehlgeschlagen! Bitte überprüfe deine Internetverbindung.',
```

2020-08-20 19:41 UTC, antonplagemann commented on packages/frontend/src/components/moodle/SetCourseNotifications.vue
> +              'Anfrage fehlgeschlagen! Bitte überpüfe deine Internetverbindung.',
```suggestion
              'Anfrage fehlgeschlagen! Bitte überprüfe deine Internetverbindung.',
```

2020-08-20 19:41 UTC, antonplagemann commented on packages/frontend/src/components/moodle/SetRefreshRate.vue
> +              'Anfrage fehlgeschlagen! Bitte überpüfe deine Internetverbindung.',
```suggestion
              'Anfrage fehlgeschlagen! Bitte überprüfe deine Internetverbindung.',
```

2020-08-20 19:41 UTC, antonplagemann commented on packages/frontend/src/store/utils/ApiUtil.js
> +const URL = 'http://localhost:4040/api';
Diese hardcoded URL ist immer noch hässlich, auch in einer neuen Datei...

2020-08-20 19:41 UTC, antonplagemann commented on packages/frontend/src/store/utils/StoreUtil.js
> +    // state.data = null;
Warum auskommentiert und nicht entfernt?
```suggestion
```

2020-08-20 19:41 UTC, antonplagemann commented on packages/frontend/src/views/Login.vue
> +              >Github Repository</a> &nbsp;·&nbsp;
Was ist das für ein Zeichen dazwischen?
```suggestion
              >Github Repository</a> &nbsp;&nbsp;
```

2020-08-20 19:41 UTC, antonplagemann commented on packages/frontend/src/views/Login.vue
> +                'Anfrage fehlgeschlagen! Bitte überpüfe deine Internetverbindung.',
```suggestion
                'Anfrage fehlgeschlagen! Bitte überprüfe deine Internetverbindung.',
```

2020-08-20 19:41 UTC, antonplagemann commented on packages/frontend/src/views/Login.vue
> +                'Anfrage fehlgeschlagen! Bitte überpüfe deine Internetverbindung.',
```suggestion
                'Anfrage fehlgeschlagen! Bitte überprüfe deine Internetverbindung.',
```

2020-08-21 07:39 UTC, tjarbo commented on packages/frontend/src/store/utils/StoreUtil.js
> +    // state.data = null;
Das möchte ich mal zur Vollständigkeit der Utility drinnen behalten. Das Problem trat nämlich auf, wenn man die Kursliste bearbeitet (Benachrichtigungen). Durch das Leeren von `state.data` verschwand immer die ganze Kursliste, bis die Anfrage vollständig endete. Sah irgendwie unschön aus. Da ich aber noch nicht zu 100% sicher bin, dass dies keine Auswirkung auf andere Bereiche der App haben wird, lasse ich es vorsichtshalber mal drinne :smile:

2020-08-21 07:40 UTC, tjarbo commented on packages/frontend/src/store/utils/ApiUtil.js
> +const URL = 'http://localhost:4040/api';
I know :laughing:. Das ganz wird in #17 angegangen und entfernt :innocent:

2020-08-21 07:41 UTC, tjarbo commented on packages/backend/src/docs/rest-api.yml
> -- "https"
Da ist was dran, dann muss ich wohl einfach http und https hinzufügen, denn sonst klappt es bei mir lokal nicht :smile:

2020-08-24 08:48 UTC, tjarbo commented on packages/backend/src/docs/rest-api.yml
> -- "https"
Habe beide Schemes wieder hinzugefügt (default `http` für die Entwicklung)

2020-08-24 09:03 UTC, tjarbo commented on packages/frontend/src/views/Login.vue
> +              >Github Repository</a> &nbsp;·&nbsp;
Das ist ein optischer Trenner - jap der ist auf der Oberfläche sichtbar :smile:

2020-08-24 11:14 UTC, tjarbo commented
So delle, folgende neue Änderungen:
* Das Problem mit dem Logout-Button ist behoben, bzw das vielfache Weiterleiten beim Öffnen der Seite.
* Das Problem mit dem "Zurückgehen" auf das Dashboard nach dem Abmelden ist behoben.
* Das Anzeigen der Meldung `Zugangs abgelaufen ....` beim erstmaligem öffnen ist behoben.
* Alle Fehlermeldungen, meist verursacht durch vue-router, sind behoben.

Was noch offen ist, aber das in einem eigenen Issue behoben werden sollte:
* Fehlermeldungen vom Server sind auf Englisch.
* HTTP-Dokumentation ist irgendwie broke (Responses werden nicht mehr richtig angezeigt)

2020-08-24 12:26 UTC, antonplagemann requested changes
Code sieht echt top aus 👍 
Ich glaub nur die Regex Anpassung in `AddAdministrator.vue` fehlt noch oder?
Ich mach noch einen Live-Test später und checke deine Bugfix-Liste :-)

2020-08-24 13:23 UTC, tjarbo commented
> Code sieht echt top aus +1
> Ich glaub nur die Regex Anpassung in `AddAdministrator.vue` fehlt noch oder?
> Ich mach noch einen Live-Test später und checke deine Bugfix-Liste :-)
@antonplagemann

Sehr cool :+1: Vielen Dank! Habe gerade nochmal die RegEx im Frontend angepasst - hatte es vergessen gehabt :sweat_smile:

2020-08-24 17:16 UTC, antonplagemann approved these changes
> So delle, folgende neue Änderungen:
> 
>     * Das Problem mit dem Logout-Button ist behoben, bzw das vielfache Weiterleiten beim Öffnen der Seite.
> 
Bestätigt, tut alles wieder, nice!
>     * Das Problem mit dem "Zurückgehen" auf das Dashboard nach dem Abmelden ist behoben. Fixed #21
> 
Jup
>     * Das Anzeigen der Meldung `Zugangs abgelaufen ....` beim erstmaligem öffnen ist behoben.
> 
Tut 👍 
>     * Alle Fehlermeldungen, meist verursacht durch vue-router, sind behoben.
> 
> 
Hab nichts mehr finden können :-)
> Was noch offen ist, aber das in einem eigenen Issue behoben werden sollte:
> 
>     * Fehlermeldungen vom Server sind auf Englisch.
> 
Hm, low prio würd ich sagen :-)
>     * HTTP-Dokumentation ist irgendwie broke (Responses werden nicht mehr richtig angezeigt)
Doku tat bei mir problemlos (HTTPS)

Was mir auffiel war das mein Moodle Token nicht mehr tat. Das Gefährliche dabei ist das ich das nicht mitbekomme, außer dadurch das die Kurse im Dashboard nicht geladen werden (die Kursliste-Methode (API) kriegt einen Fehler von der fetch-Methode und löst den catch-Block aus => `Courses could not be loaded`...). Vlt. wäre das noch ein Issue wert, sowas wie "Benachrichtigung an User bei ungültigem Token", sonst errort das Ding so vor sich hin wie bei mir (wer weiß schon wie lange) :-)

2020-08-24 18:18 UTC, merged