Feature/issue 18
tjarbo/discord-moodle-bot pull request #52
Opened 2020-08-31 21:14 UTC by antonplagemann

> **Als ein** User
> **will ich** im Dashboard die vorhandenen Administratoren sehen,
> **sodass** ich diese einfach verwalten und z. B. entfernen kann.

## Beschreibung

Closes #18 
Diese PR führt ein neues Element im Tab `Administration` im Dashboard sowie zwei neue API Endpunkt dafür ein.
Neu hinzugekommen ist eine Tabelle welche die aktuell hinterlegten Administratoren anzeigt (siehe Screenshots).
Mithilfe von Checkboxen ist es dann auch möglich einen oder mehrere Administratoren zu löschen.
Die Daten hierfür liefert der neue GET /api/settings/administrator Endpunkt.
Das Löschen übernimmt der neue DELETE /api/settings/administrator/:userId Endpunkt.
Die neuen Endpunkte wurden in die Swagger API Dokumentation aufgenommen.
Evtl. TODO: Unit Tests hinzufügen.
### Screenshots:
![grafik](https://user-images.githubusercontent.com/54081139/91769061-f130dd80-ebde-11ea-8e6c-94d61f8a6e8c.png)

### Art der Änderungen:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## Checkliste

- [x] Make sure you are requesting to development. Don't request to master branch!
- [x] I have linked the related issue.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-09-01 06:57 UTC, tjarbo requested changes
Aus der Sicht der Security sollte es nicht so sein, dass die Blockade zum Löschen des letzten Admins nur vom Frontend abhängig ist. Erweitere doch das Admin-Schema um eine `deleteable`Eigenschaft, welches per default false gesetzt ist und nur beim initialem Admin auf true steht. Daran orientiert sich dann das Backend während des Löschens. Es gilt immer: Trust no user input!

2020-09-01 06:57 UTC, tjarbo commented on packages/backend/src/controllers/administrator/index.ts
> +}).unknown(true);
Würde hier nur direkt das `params` objekt validieren und nicht die ganze Request. Das ist ein wenig rechenaufwendig und würde etwas zu ungenau sein

2020-09-01 06:57 UTC, tjarbo commented on packages/backend/src/controllers/administrator/index.ts
> +        });
Schönes "sanitizing" :+1: Gefällt mir

2020-09-01 06:57 UTC, tjarbo commented on packages/backend/src/docs/rest-api.yml
> +            $ref: "#/definitions/ApiResponse"
Ein erfolgreicher Löschung ohne Weitere Fehlermeldungen sollte der HTTP-Code 204 anstelle von 200 verwendet werden. (Erstbester Beitrag auf Stackoverflow: https://stackoverflow.com/a/29574521)

Außerdem vermisse ich noch `Bad Request` :bat: :superhero:

2020-09-01 06:57 UTC, tjarbo commented on packages/frontend/src/components/administration/AddAdministrator.vue
> +          this.$store.dispatch('getAdministrators');
:+1:

2020-09-01 06:57 UTC, tjarbo commented on packages/frontend/src/components/administration/AdministratorList.vue
> +        if (apiResponse.code) notifyFailure(apiResponse.error[0].message);
Hier fehlt das `return` da sonst zwei Fehlermeldungen angezeigt werden.

2020-09-01 06:57 UTC, tjarbo commented on packages/frontend/src/components/administration/AdministratorList.vue
> +        .then(() => {
:+1:

2020-09-01 06:57 UTC, tjarbo commented on packages/frontend/src/store/modules/administration.js
> +    GET_ADMINISTRATORS(state, payload) {
- Die Mutations beziehen sich nur auf den `state`. Sie sollten daher alle `SET_...` heißen. 
- Können wir aus beiden nur ein `state` machen ? - Denn der eine speichert nicht wirklich was. Die Anfrage `POST /settings/administrators` gibt dann einfach bei der Anfrage alle Administratoren zurück. Diese können dann im State gespeichert werden - ein zusätzliches triggern zu aktualisieren der Tabelle ist nicht notwendig und würde eine Request sparen

2020-09-01 06:57 UTC, tjarbo commented on packages/frontend/src/store/modules/administration.js
> +    GET_ADMINISTRATORS(state, payload) {
Wäre cool, wenn wir sowas vorher im Issue besprechen könnten, damit das nicht erst während der PR zum tragen kommt - da hat man nämlich wenig Lust nochmal alles zu ändern :sleeping:

2020-10-09 06:27 UTC, tjarbo commented on packages/backend/src/controllers/administrator/index.ts
> +}).unknown(true);
Done in 2d029885b45f26cabc27728e7f013714c19f49cd :white_check_mark:

2020-10-09 06:58 UTC, tjarbo commented on packages/frontend/src/components/administration/AdministratorList.vue
> +        if (apiResponse.code) notifyFailure(apiResponse.error[0].message);
Done in 87f5244

2020-10-09 07:00 UTC, tjarbo commented on packages/backend/src/docs/rest-api.yml
> +            $ref: "#/definitions/ApiResponse"
Done in 71d7091

2020-10-09 16:34 UTC, tjarbo approved these changes

2020-10-09 16:40 UTC, antonplagemann commented on packages/frontend/src/store/modules/administration.js
> +              console.log('## resolve');
```suggestion
```

2020-10-09 16:40 UTC, antonplagemann commented on packages/frontend/src/store/modules/administration.js
> +              console.log('## reject');
```suggestion
```

2020-10-09 16:45 UTC, tjarbo approved these changes

2020-10-09 16:46 UTC, merged