Feature/82 easy deployment with heroku
tjarbo/discord-moodle-bot pull request #85
Opened 2021-01-28 21:55 UTC by tjarbo

> **As a** User
> **I want to** host the fmdb in the cloud and deploy it with "one" click
> **because** I am not familiar with docker and my fmdb should run 24/7

## Description
This is issue #82. I have added a entire new wiki article to setup a fmdb with Heroku and MongoDB Atlas.
https://github.com/tjarbo/discord-moodle-bot/wiki/Setup-with-heroku-and-mongodb-atlas

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## Checklist

- [ ] ~Make sure you are requesting to development. Don't request to master branch!~
- [x] I have linked the related issue.
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-01-28 22:13 UTC, p-fruck requested changes
Sieht gut aus, aber einen schwerwiegenden Fehler möchte ich anmerken :P

2021-01-28 22:13 UTC, p-fruck commented on app.json
> +      "description": "Discord-Id of the initial administrator. More can be added later vie webinterface."
```suggestion
      "description": "Discord-Id of the initial administrator. More can be added later via webinterface."
```

2021-01-29 08:23 UTC, antonplagemann requested changes
Habe auch noch schwerwiegende Fehler gefunden :-D
Sieht gut aus ;-)

2021-01-29 08:23 UTC, antonplagemann commented on app.json
> +      "description": "If the remaining time of a submission is less than the specified time, a notification will be sind. Time in seconds.",
```suggestion
      "description": "If the remaining time of a submission is less than the specified time, a notification will be sent. Time in seconds.",
```

2021-01-29 08:23 UTC, antonplagemann commented on app.json
> +      "description": "Use the course form or the full course name in Discord messages.",
Wäre einheitlicher, außerdem habe ich die Formulierung davor nicht ganz verstanden :-)
```suggestion
      "description": "Whether to use short- or fullname of the courses in the discord message",
```

2021-01-29 11:17 UTC, antonplagemann approved these changes

2021-01-29 15:34 UTC, tjarbo commented
Nooo... GitHub, was kannst du eigentlich 🙄 Bitte nochmal approven @antonplagemann

2021-01-29 16:31 UTC, antonplagemann approved these changes
Und es ist sogar noch schöner geworden! 🎉

2021-01-29 16:49 UTC, tjarbo commented
> Und es ist sogar noch schöner geworden! tada

:laughing:

2021-01-29 20:49 UTC, merged